[workspace]
resolver = "2"
members = [
  "services/pool-verifier",
  "services/template-manager",
  "services/rg-protocol",
  "services/sv2-bridge"
]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.92"
