[package]
name = "rg-protocol"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
anyhow = "1"