name: rust

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust stable
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Show tree (debug)
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -name Cargo.toml

      # CHANGE THIS LINE IF YOUR Cargo.toml IS NOT AT REPO ROOT
      - name: fmt
        run: cargo fmt --all --check --manifest-path services/Cargo.toml

      - name: clippy
        run: cargo clippy --all-targets --all-features -D warnings --manifest-path services/Cargo.toml

      - name: test
        run: cargo test --all --manifest-path services/Cargo.toml
